language: php

php:
  - 5.6

cache:
  timeout: 3600
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  - sudo sed -i.bak "s/max_allowed_packet *= *.*/max_allowed_packet = 128M/g" /etc/mysql/my.cnf
  - sudo sed -i.bak "s/wait_timeout *= *.*/wait_timeout = 68800/g" /etc/mysql/my.cnf
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer self-update
  - composer global require drush/drush:dev-master --prefer-source
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - echo "$(curl -fsSL https://gist.githubusercontent.com/nickveenhof/11386315/raw/b8abaf9304fe12b5cc7752d39c29c1edae8ac2e6/gistfile1.txt)" | sed -e "s,PATH,$TRAVIS_BUILD_DIR/../drupal,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth 1 --branch 8.2.x http://git.drupal.org/project/drupal.git
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

before_script:
  - cd $TRAVIS_BUILD_DIR/../drupal
  - composer install
  - drush -v site-install standard --db-url=mysql://root:@localhost/drupal --yes
  - drush en --yes simpletest
  - composer config repositories.drupal composer https://packages.drupal.org/8
  # - composer require drupal/search_api_solr:1.0-alpha3
  - cp -r ../acquia-connector modules/
  - drush en --yes acquia_connector
  - drush cr
  - sudo service mysql restart


script:
  - export SIMPLETEST_DB=mysql://root:@localhost/drupal
  - php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://localhost --class 'Drupal\acquia_connector\Tests\AcquiaConnectorSpiTest' | tee /tmp/test.txt ; export TEST_EXIT=${PIPESTATUS[0]} ; echo $TEST_EXIT
  - TEST_OUTPUT=$(! egrep -i "([1-9]+[0-9]* fails?)|([1-9]+[0-9]* exceptions?)|(fatal)" /tmp/test.txt > /dev/null)$?
  # Add some more info
  - php -i | grep 'php.ini'
  - sudo cat /var/log/apache2/error.log
  # Exit the build
  - echo $TEST_EXIT
  - echo $TEST_OUTPUT
  - if [ $TEST_EXIT -eq 0 ] && [ $TEST_OUTPUT -eq 0 ]; then exit 0; else exit 1; fi
