language: php

php:
  - 5.6

cache:
  timeout: 3600
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:dev-master --prefer-source
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo service apache2 restart
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth 1 --branch 8.2.x http://git.drupal.org/project/drupal.git
  - curl -v "http://localhost"

before_script:
  - cd $TRAVIS_BUILD_DIR/../drupal
  - drush -v site-install standard --db-url=mysql://root:@localhost/drupal --yes
  - drush en --yes simpletest

script:
  - echo "Hello!"
