# Schema for the configuration files of the acquia_search module.
acquia_search.settings:
  type: config_object
  label: 'Acquia search settings'
  mapping:
    host:
      type: string
      label: Acquia search host
    path:
      type: string
      label: 'Acquia search path'
    derived_key_salt:
      type: string
      label: 'Acquia derived key salt'
    version:
      type: string
      label: 'Acquia Search version'

plugin.plugin_configuration.search_api_solr_connector.solr_acquia_connector:
  type: plugin.plugin_configuration.search_api_solr_connector.standard
  label: Acquia Search Solr connector settings
